# Generated by Django 5.2.6 on 2025-10-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_user_alter_movie_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
